; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-sticks3

[env]
lib_extra_dirs = ../M5GFX, ../M5Unified
# lib_extra_dirs = ../uiflow_micropython/m5stack/components/M5GFX, ../uiflow_micropython/m5stack/components/M5Unified
lib_deps =
    https://github.com/m5stack/M5PM1.git
    https://github.com/m5stack/M5IOE1.git

[env:m5stack-sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp> -<audio_example.cpp> -<imu_example.cpp>
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1


[env:m5stack-tab5-p4]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
framework = arduino
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
build_src_filter = +<main.cpp> -<audio_example.cpp> -<imu_example.cpp>
build_flags =
    -DESP32P4
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1


[env:m5stack-stickcplus-hat18650c]
platform = espressif32@6.12.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_src_filter = -<*> +<hat18650c_test.cpp>
lib_deps =
    symlink://../examples/m5hat-18650c
build_unflags =
    -DARDUINO_M5Stick_C
build_flags =
    -DARDUINO_M5Stick_C_Plus
    -DCORE_DEBUG_LEVEL=5
