; StampP4X board-detection validation

[platformio]
default_envs = m5stack-stampp4x

[env]
lib_extra_dirs = ../M5GFX, ../M5Unified

[env:m5stack-stampp4x]
platform = espressif32
board = esp32-p4_r3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_src_filter = -<*> +<stamp_p4x_test.cpp>
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_ID=156
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
